### ISSUE TITLE
Incorrect link to Kubernetes Workload Attestation Plugin

### ISSUE THREAD

**Issue by mpuncel** [spiffe/spiffe.io#101]
The link at https://spiffe.io/spire/docs/configuring/#workload-attestation-for-workloads-scheduled-by-kubernetes to the "corresponding SPIRE documentation for the Kubernetes Workload Attestor plugin" actually goes to documentation about Azure node attestation.

**Comment by sanderson042** [comment]
Thanks for catching that! Fixed in PR #107.
