### ISSUE TITLE
Misspelling of Grey Matter / missing hyperlink

### ISSUE THREAD

**Issue by brianlitalien** [spiffe/spiffe.io#108]
Grey Matter appears misspelled in the Comparisons write up currently showing on https://spiffe.io/spire/comparisons/

Should be "Grey" vice Gray.

The name should also hyperlink to https://greymatter.io if possible.

Thanks!

**Comment by joshua-rutherford** [comment]
@brianlitalien, we'll go ahead and open the pull request to fix this ourselves.  @zoemccormick, since you noticed this can you open the pull request?
