### ISSUE TITLE
Updates for 0.11.0 SPIRE release

### ISSUE THREAD

**Issue by marcosy** [spiffe/spiffe.io#165]
I have scanned the site looking for updates that needs to be done, according to the [changelog](https://github.com/spiffe/spire/pull/1785/files), once SPIRE 0.11.0 is released.
Here is what I found:

- SPIFFE and SPIRE are now CNCF incubation projects, not sandbox (bottom of the main page https://spiffe.io/ , just before the CNCF logo).

- AWS node resolver has been deprecated and absorbed by AWS node attestor. We should:
  - Update the [image](https://spiffe.io/img/server.png) to reflect this.
  - Update step 10 in "_day in the live of an SVID_". Perhaps another attestor can be used as example.

- The datastore plugin is no longer pluggable. We should delete/reprhase the following text in [custom plugins section](https://github.com/spiffe/spiffe.io/blob/master/content/docs/latest/spire/understand/concepts.md#custom-server-and-agent-plugins): _" Or you could create a custom datastore plugin to support a type of database SPIRE doesn’t currently support"_

**Comment by mchurichi** [comment]
Fixed in #171
