### ISSUE TITLE
Add search to documentation site

### ISSUE THREAD

**Issue by anvega** [spiffe/spiffe.io#183]
Navigation of the documentation site is limited to the nav bar and there is no option for readers to search the site.

A search box and a search page and allow readers will help readers find the information they are looking for faster. There are options available like GCSE, Algolia, or Lunr to evaluate and pick one that best fits the need.  

As a side note:  spiffe.io/docs/ displays an empty page.

**Comment by sanderson042** [comment]
Algolia looks promising as a search tool for spiffe.io. Here's some details:

The SPIFFE sponsor CNCF mentioned that Algolia offers their service for free to open source projects. To get the free service the open source project needs to apply using the Open Source tab [on this page](https://www.algolia.com/for-open-source/). 

Algolia also offers [free service](https://www.algolia.com/pricing/) to anyone using less than 10,000 searches per month without needing to apply.

Algolia is used by another CNCF project, Open Policy Agent, for [their documentation](https://www.openpolicyagent.org/docs/latest/).

**Comment by mchurichi** [comment]
hey @anvega, why did we close this issue? is it something we're not going to do?

**Comment by anvega** [comment]
Hello @mchurichi. Me cleaning up on issues I opened long ago. I don't recall what the motivation behind it was. I may be biased due to my familiarity with the site but it doesn't take me long to find information in the documentation section.
