### ISSUE TITLE
Remove mention of deprecated "enable_sds" SPIRE Agent configuration option

### ISSUE THREAD

**Issue by rturner3** [spiffe/spiffe.io#189]
The [Using Envoy with SPIRE](https://spiffe.io/docs/latest/spire-integrations/envoy/envoy/) page references a SPIRE Agent configuration value `enable_sds` that is deprecated as of https://github.com/spiffe/spire/commit/ba51645880710e8b499c7e9b4b6e36ff3c9e72dc and will be removed in the 0.12.0 release of SPIRE.

The documentation on spiffe.io should be updated to not suggest that users set the deprecated `enable_sds` configuration value.

**Comment by mchurichi** [comment]
Fixed by https://github.com/spiffe/spiffe.io/pull/191
