### ISSUE TITLE
cli healthcheck -socketPath option in documentation out of date

### ISSUE THREAD

**Issue by caleygoff-invitae** [spiffe/spiffe.io#200]
Hi! Along the journey of setting up the spire-server I noticed that for the healthcheck, the documentation doesn't actually match the options in the actual cli. 
The documentation https://spiffe.io/docs/latest/deploying/spire_server/#spire-server-healthcheck says

Command | Action | Default
-- | -- | --
-shallow | Perform a less stringent health check |  
-socketPath | Path to the SPIRE Server API socket | /tmp/spire-server/private/api.sock
-verbose | Print verbose information

but the actual cli says 
```
/opt/spire # /opt/spire/bin/spire-server healthcheck -socketPath /tmp/spire/spire-registration.sock
flag provided but not defined: -socketPath
Usage of health:
  -registrationUDSPath string
    	Registration API UDS path (default "/tmp/spire-registration.sock")
  -shallow
    	Perform a less stringent health check
  -verbose
    	Print verbose information
/opt/spire # /opt/spire/bin/spire-server healthcheck -registrationUDSPath /tmp/spire/spire-registration.sock
Server is healthy.
```

I am running `gcr.io/spiffe-io/spire-server:0.11.2`

Note: the url above says latest, but I'm not sure how to change the version of the documentation on the webpage. 

Thanks!

**Comment by mchurichi** [comment]
Hey @caleygoff-invitae, thanks for reporting this.

It should be already fixed by https://github.com/spiffe/spiffe.io/pull/214 so I'm closing this, but feel free to reopen it if you find any other related issue.
