### ISSUE TITLE
Latest Release Version

### ISSUE THREAD

**Issue by vijaymateti** [spiffe/spiffe.io#210]
The latest release version is being picked up incorrectly on multiple pages

Its showing up as 0.8.5 instead of 0.12.1
https://spiffe.io/downloads/#spire-releases
https://spiffe.io/docs/latest/deploying/install-agents/
https://spiffe.io/docs/latest/deploying/install-server/

The the latest tag short code says use the index 0 on the release json
https://api.github.com/repos/spiffe/spire/releases

May be this needs to point to the api
https://api.github.com/repos/spiffe/spire/releases/latest

**Comment by dfeldman** [comment]
@mchurichi I believe you are already working on this? Can you assign this to yourself?

**Comment by mchurichi** [comment]
@dfeldman sure!, I'll be pushing a fix shorty
