### ISSUE TITLE
Exclusionary expression found in spiffe.io

### ISSUE THREAD

**Issue by wibarre** [spiffe/spiffe.io#241]
Exclusionary expression “whitelisted” found in [spiffe.io](http://spiffe.io/) site ( https://spiffe.io/docs/latest/deploying/configuring/), Service Accounts Tokens section.

Previous issue: Formalize policy and removal of exclusionary language in SPIRE spiffe/spire#2003

**Comment by wibarre** [comment]
I will go ahead an submit a PR for this one.

**Comment by azdagron** [comment]
Thank you so much @wibarre .
