### ISSUE TITLE
PR preview assets wrongly published to prod?

### ISSUE THREAD

**Issue by c4rlo** [spiffe/spiffe.io#273]
https://spiffe.io currently has:

```html
<link rel="stylesheet" href="https://deploy-preview-272--spiffe.netlify.app/css/style.1db1f4238dfe329e043f994d70fa2006780c816bd84f444fe31b09794695a59e.css">
```

(and several other references to that domain)

Note that `deploy-preview-272` in there. Looks like that comes from #272, which somehow got accidentally pushed to prod?

Normally, the website still looks okay; except that on our corporate network, https://deploy-preview-272--spiffe.netlify.app/ is blocked, so there it looks completely broken because of this.

**Comment by mchurichi** [comment]
Hi @c4rlo, thanks for reporting this.
Seems like some recent testing of the features implemented by #272 impacted on prod, most likely this is a messed up Netlify config. I'm taking a look and report back shortly.

**Comment by mchurichi** [comment]
This should be fixed now, @c4rlo could you please confirm?

**Comment by c4rlo** [comment]
Yes, this is now fixed for me. Thanks for the quick response!
