### ISSUE TITLE
 https://spiffe.io/ looks perfect but https://www.spiffe.io/ rendering incorrectly 

### ISSUE THREAD

**Issue by jennybeth** [spiffe/spiffe.io#38]
@lucperkins 

From my colleague Ryan:

"Subresource Integrity: The resource '<URL>' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced."
... https://spiffe.io/ works fine.   https://www.spiffe.io/ does not because it's pulling objects from spiffe.io without the www.

"Subresource Integrity: The resource 'https://spiffe.io/css/style.0cd2e5ed6f75f740cd302227a0f8316ff38d9b59dc52d08ea6dd4f58eea4b01d.css' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.

**Comment by lucperkins** [comment]
My temporary solution is to set the base URL to `/`. That's fixed the issue but I'd like to explore better alternatives.
