### ISSUE TITLE
Building SPIRE from Source is appearing in top navbar for docs but should not, for IA reasons

### ISSUE THREAD

**Issue by jennybeth** [spiffe/spiffe.io#43]
Hi, Luc. This looks like useful content but from an Information Architecture perspective it is not substantial enough to be called out in the top navbar of what is now the temporary docs landing page. 

I'm happy to have a conversation about what kinds of docs I'm okay with calling out in a top navbar.

@lucperkins 

Thanks,
Jenny Beth

**Comment by lucperkins** [comment]
I wasn’t aware that not all docs are included in the navbar. In the future, feel free to simply change the status of a doc.

**Comment by jennybeth** [comment]
Okay, cool. I don't know where, in the code, I do that.

**Comment by lucperkins** [comment]
Oh, I thought maybe there was a system in place to select which docs appear in the navbar. There is currently no such system. I can set one up.

**Comment by jennybeth** [comment]
Ah, ok. 

Well where, in the code, does it currently say to link all docs to that navbar?

**Comment by lucperkins** [comment]
@jennybeth The navbar is automatically generated and includes all docs.

https://github.com/spiffe/spiffe.io/blob/master/layouts/partials/navbar.html#L6

I've now included some logic that enables you to exclude a doc by setting `navbar: false` in the page metadata.

**Comment by jennybeth** [comment]
Oh, brilliant! Thank you, as always, for your speedy help.
