### ISSUE TITLE
List of doc title links lower down also containing unwanted items, can we fix?

### ISSUE THREAD

**Issue by jennybeth** [spiffe/spiffe.io#47]
At https://spiffe.io/spire/:

Top navbar now correctly hiding documents who have "navbar: false" set in their metadata. 

We also need to hide these same documents from the list of links that appears in a line below the title.

@lucperkins

**Comment by lucperkins** [comment]
But if those docs are not shown there, they will be completely undiscoverable on the website

**Comment by jennybeth** [comment]
Ah, understood.

I'll leave this be for now and we can revisit once I have an Information Architecture plan in place for the spiffe.io website.  

Thanks,
Jenny Beth
